job-defaults: &job-defaults
  resource_class: xlarge
  docker:
    - image: cimg/node:lts

version: 2.1

orbs:
  sonarqube: elateral/sonarqube-scanner@1.2.0

jobs:
  prepare:
    <<: *job-defaults
    steps:
      - run:
          name: add github known hosts
          command: |
            mkdir -p ~/.ssh
            echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl " >> ~/.ssh/known_hosts
            echo "github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg= " >> ~/.ssh/known_hosts
            echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=" >> ~/.ssh/known_hosts
      - run:
          name: checkout code
          command: git clone -b "$CIRCLE_BRANCH" --single-branch "git@github.com:ElateralLtd/brandgility-embedded-demo.git" .
      - run:
          name: Add npmjs.org token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_RO" >> ./.npmrc
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install packages
          command: yarn --pure-lockfile --no-progress
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Prepare .env
          command: |
            echo NODE_ENV=production >> .env
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  vulnerability-audit:
    <<: *job-defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Check Tools Versions
          command: |
            jq --version
      - run:
          name: make audit folder
          command: |
            mkdir -p audit
      - run:
          name: Run audit
          command: |
              export PATH="$(yarn global bin):$PATH"; \
              yarn global add yarn-audit-html@4.0.0; \
              set +e;
              yarn audit --groups dependencies --json > audit/audit-results-yarn.json; \
              yarn audit --groups dependencies --json | yarn-audit-html --output audit/yarn-audit.html; \
              yarn audit:convert --fileIn audit/audit-results-yarn.json --fileOut audit/sonar-dep-vulns.json; \
              set -e; exit 0
      - run:
          name: Summary collect
          command: |
            chmod +x ./bin/summary-yarn.sh
            ./bin/summary-yarn.sh >> audit/audit-summary-yarn
      - store_artifacts:
          path: ./audit
      - persist_to_workspace:
          root: .
          paths:
            - audit

  build:
    <<: *job-defaults
    steps:
       - attach_workspace:
           at: .
       - run:
           name: Build
           command: yarn run build
       - persist_to_workspace:
           root: .
           paths:
            - dist/*

  deploy:
    <<: *job-defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Add github to known hosts
          command: |
            mkdir -p ~/.ssh
            echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl " >> ~/.ssh/known_hosts
            echo "github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg= " >> ~/.ssh/known_hosts
            echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=" >> ~/.ssh/known_hosts
      - run:
          command: yarn run deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - prepare:
          context: org-global
      - build:
          context: org-global
          requires:
            - prepare
      - vulnerability-audit:
          context: org-global
          requires:
            - build
      - deploy:
          context: org-global
          requires:
            - build
