job-defaults: &job-defaults
  docker:
    - image: circleci/node:14.5.0

version: 2
jobs:
  prepare:
    <<: *job-defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install packages
          command: yarn --pure-lockfile --no-progress
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Prepare .env
          command: |
            echo NODE_ENV=production >> .env
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  build:
    <<: *job-defaults
    steps:
       - attach_workspace:
           at: .
       - run:
           name: Build
           command: yarn run build
       - persist_to_workspace:
           root: .
           paths:
            - dist/*
  vulnerabilityAudit:
    docker:
      - image: circleci/node:14.16.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Check Tools Versions
          command: |
            echo "jq version: $(jq --version)"
            echo "yarn version: $(yarn --version)"
      - run:
          name: make audit folder
          command: mkdir -p audit
      - run:
          name: Install "audit-html tools"
          command: |
            sudo yarn global add yarn-audit-html
            sudo npm install -g npm-audit-html
      - run:
          name: Create yarn html report
          command: |      
            set -x; set +e; yarn audit --json | yarn-audit-html --output audit/yarn-audit.html; set -e; exit 0
      - run:
          name: Create audit jsons
          command: |
            set -x; set +e; \
            yarn audit --json > audit/audit-results-yarn.json; \
            echo "yarn version: $(yarn --version)" > audit/audit-summary-yarn; chmod 666 audit/audit-summary-yarn; \
            set -e; exit 0
      - run:
          name: Summary collect
          command: |
            bin/summary-yarn.sh >> audit/audit-summary-yarn
      - store_artifacts:
          path: ./audit
  deploy:
    <<: *job-defaults
    steps:
      - attach_workspace:
          at: .
      - deploy:
          command: yarn run deploy

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - prepare:
          context: org-global
      - build:
          context: org-global
          requires:
            - prepare
      - vulnerabilityAudit:
          context: org-global
          requires:
            - build
      - deploy:
          context: org-global
          requires:
            - build
